sudo: required
language: node_js
node_js:
  - "10"
services:
  - postgresql
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script:
  - cp config.travis.js config.js
  - psql -c 'create database travis_ci_test;' -U postgres
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm i -g npm@^3
  - npm start &
  - sleep 3
